project:
  type: website
  output-dir: docs
  
website: 
  title: "FMDV Preclinical"
  navbar:
    left:
      - href: preprocess.qmd
        text: Preprocessing 
      - href: incubation.qmd
        text: Incubation
      - href: latent.qmd
        text: Latent
      - href: subclinical.qmd
        text: Subclinical
      - href: serial_interval.qmd
        text: Fractional
      - href: longitudinal.qmd
        text: Longitudinal
      - href: compartmental.qmd
        text: Simulation
    right:
      - href: https://geoepi.github.io/
        text: GeoEpi
      - icon: github
        href: https://github.com/geoepi/fmdv-preclinical
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"

format:
  html:
    theme: lux
    toc: true
    
editor: source

