project:
  type: website
  output-dir: docs
  
website: 
  title: "FMDV Preclinical"
  navbar:
    left:
      - href: preprocess.qmd
        text: Preprocessing 
      - href: incubation.qmd
        text: Duration
      - href: rooms.qmd
        text: Room-to-Room
      - href: herd.qmd
        text: Within-Herd
      - href: network.qmd
        text: Between-Farm
    right:
      - href: https://github.com/geoepi/fmdv-preclinical
        text: GeoEpi
      - icon: github
        href: https://github.com/geoepi/fmdv-preclinical
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"

format:
  html:
    theme: lux
    toc: true
    
editor: source

