num_donors: 1
total_herd_size: 100
contact_rate: 0.15
num_hours: 720
delta_t: 1
dose_scaling_factor: 10
dose_max_efficiency: 0.4
dose_efficiency_at_threshold: 0.15
dose_threshold: 0.8
nasal_threshold_mean: 7.8
nasal_threshold_sd: 0.2
serum_threshold_mean: 6.7
serum_threshold_sd: 0.2
infect_threshold_mean: 6.1
infect_threshold_sd: 0.2
growth_rate_nasal_mean: 3.1
growth_rate_nasal_sd: 0.2
growth_rate_serum_mean: 2.6
growth_rate_serum_sd: 0.2
clearance_rate_mean: 0.6
clearance_rate_sd: 0.2
stochastic_noise_mean: 0.5
stochastic_noise_sd: 0.2
exponential_factor_mean: 1.1
exponential_factor_sd: 0.2
inflection_point_mean: 5.6
inflection_point_sd: 0.2
growth_cease_mean: 120
growth_cease_sd: 2
nasal_ccap_mean: 10
nasal_ccap_sd: 0.2
serum_ccap_mean: 9
serum_ccap_sd: 0.2
preclin_infect: FALSE
recovery_time_mean: 12
recovery_time_sd: 1
